services:
  flutter:
    build:
      context: .
      target: flutter
      args:
        flutter_version: $FLUTTER_VERSION
  
  android:
    build:
      context: .
      target: android
      args:
        flutter_version: $FLUTTER_VERSION
        android_build_tools_version: $ANDROID_BUILD_TOOLS_VERSION
        platforms_versions: $PLATFORMS_VERSIONS

  test:
    build:
      context: .
      target: android-test
      args:
        flutter_version: $FLUTTER_VERSION
        android_build_tools_version: $ANDROID_BUILD_TOOLS_VERSION
        platforms_versions: $PLATFORMS_VERSIONS
    working_dir: /home/flutter/test_app/android
