on:
  push:
    branches:
      - main
    paths:
      - Dockerfile
      - test/**
      - config/version.json
      - .github/workflows/build_push_image.yml

jobs:
  build_push_android:
    permissions:
      packages: write
      contents: read
    runs-on: ubuntu-latest
    env:
      AWS_REGION: us-east-1
      IMAGE_REPOSITORY_NAME: flutter-android
      ANDROID_BUILD_TOOLS_VERSION: 30.0.3
      # ANDROID_PLATFORM_VERSIONS: 28 31 33
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Quay.io
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_ROBOT_TOKEN }}

      - name: Login to ECR Public
        uses: docker/login-action@v2
        with:
          # AWS_REGION needs to be defined in the parent scope
          registry: public.ecr.aws
          username: ${{ secrets.AWS_ACCESS_KEY_ID }}
          password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Create ECR repository for final images
        uses: int128/create-ecr-repository-action@v1
        id: ecr
        with:
          public: true
          repository: ${{ env.IMAGE_REPOSITORY_NAME }}

      - name: Update description of ECR repository for final images
        run: |
          aws ecr-public put-repository-catalog-data \
            --repository-name ${{ env.IMAGE_REPOSITORY_NAME }} \
            --catalog-data "description"="${{ github.event.repository.description }}",usageText="See About section",aboutText="$(jq -nRs 'input' docs/ecr.md | sed 's/\\n/\n/g')"

      - name: Create ECR repository for layer cache
        uses: int128/create-ecr-repository-action@v1
        id: ecr-cache
        with:
          public: true
          repository: ${{ env.IMAGE_REPOSITORY_NAME }}/cache

      - name: Set environment variables from from version.json
        run: |
          echo "FLUTTER_VERSION=$(jq -r '.flutter.version' config/version.json)" >> $GITHUB_ENV
          echo "ANDROID_PLATFORM_VERSIONS=$(jq -r '.android.platforms[].version' config/version.json)" >> $GITHUB_ENV

      - name: Set environment variable for image repository and tag
        run: |
          IMAGE_REPOSITORY_PATH="${{ github.repository_owner }}/${{ env.IMAGE_REPOSITORY_NAME }}"
          echo "IMAGE_REPOSITORY_PATH=$IMAGE_REPOSITORY_PATH" >> $GITHUB_ENV

          CACHE_REPOSITORY_PATH="ghcr.io/$IMAGE_REPOSITORY_PATH"
          echo "CACHE_REPOSITORY_PATH=$CACHE_REPOSITORY_PATH" >> $GITHUB_ENV

      - name: Load image metadata
        uses: docker/metadata-action@v4
        id: metadata
        with:
          images: |
            ${{ env.IMAGE_REPOSITORY_PATH }}
            ghcr.io/${{ env.IMAGE_REPOSITORY_PATH }}
            quay.io/${{ env.IMAGE_REPOSITORY_PATH }}
            public.ecr.aws/${{ env.IMAGE_REPOSITORY_PATH }}
          tags: |
            type=raw,value=${{ env.FLUTTER_VERSION }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build image and push to local Docker daemon
        uses: docker/build-push-action@v4
        with:
          load: true
          cache-from: ${{ env.CACHE_REPOSITORY_PATH }}:cache
          cache-to: ${{ env.CACHE_REPOSITORY_PATH }}:cache
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          target: android
          build-args: |
            flutter_version=${{ env.FLUTTER_VERSION }}
            android_build_tools_version=${{ env.ANDROID_BUILD_TOOLS_VERSION }}
            android_platform_versions=${{ env.ANDROID_PLATFORM_VERSIONS }}

      - name: Test image structure
        uses: plexsystems/container-structure-test-action@v0.3.0
        with:
          image: ${{ fromJSON(steps.metadata.outputs.json).tags[0] }}
          config: test/android_sdk_structure.yml

      # - name: Test Android build
      #   uses: docker/build-push-action@v4
      #   with:
      #     load: true
      #     cache-from: ${{ env.CACHE_REPOSITORY_PATH }}:cache-test
      #     cache-to: ${{ env.CACHE_REPOSITORY_PATH }}:cache-test
      #     tags: ${{ steps.metadata.outputs.tags }}
      #     labels: ${{ steps.metadata.outputs.labels }}
      #     target: android
      #     build-args: |
      #       flutter_version=${{ env.FLUTTER_VERSION }}
      #       android_build_tools_version=${{ env.ANDROID_BUILD_TOOLS_VERSION }}
      #       android_platform_versions=${{ env.ANDROID_PLATFORM_VERSIONS }}

      - name: Build image and push it to registries
        uses: docker/build-push-action@v4
        with:
          push: true
          # TODO: Use ECR for cache after this issue is solved https://github.com/aws/containers-roadmap/issues/876
          # cache-from: ${{ steps.ecr-cache.outputs.repository-uri }}:cache
          # cache-to: ${{ steps.ecr-cache.outputs.repository-uri }}:cache
          cache-from: ${{ env.CACHE_REPOSITORY_PATH }}:cache
          cache-to: ${{ env.CACHE_REPOSITORY_PATH }}:cache
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          target: android
          build-args: |
            flutter_version=${{ env.FLUTTER_VERSION }}
            android_build_tools_version=${{ env.ANDROID_BUILD_TOOLS_VERSION }}
            android_platform_versions=${{ env.ANDROID_PLATFORM_VERSIONS }}

      - name: Update Docker Hub description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
          repository: ${{ env.IMAGE_REPOSITORY_PATH }}
          short-description: ${{ github.event.repository.description }}
          readme-filepath: docs/readme.md
      
      # TODO: Use kaniko for building and pushing after slowness is solved
      # TODO: https://github.com/GoogleContainerTools/kaniko/issues/970
      # TODO: https://github.com/GoogleContainerTools/kaniko/issues/875
      # TODO: Use kaniko for building and pushing after pushing to Docker daemon is solved, to be able to test Docker image, with the following issues
      # TODO: https://github.com/GoogleContainerTools/kaniko/issues/1331
      # TODO: https://github.com/GoogleContainerTools/kaniko/issues/885
      # - name: Build image and push it to registries
      #   uses: int128/kaniko-action@v1
      #   with:
      #     push: true
      #     cache: true
      #     cache-repository: ${{ steps.ecr-cache.outputs.repository-uri }}
      #     tags: ${{ steps.metadata.outputs.tags }}
      #     labels: ${{ steps.metadata.outputs.labels }}
      #     build-args: |
      #       flutter_version=${{ env.FLUTTER_VERSION }}
      #       android_build_tools_version=${{ env.ANDROID_BUILD_TOOLS_VERSION }}
      #       android_platform_versions=${{ env.ANDROID_PLATFORM_VERSIONS }}
      #     kaniko-args: |
      #       --skip-unused-stages=true
      #       --use-new-run=true
      #       --snapshotMode=redo
      #     target: android
      #     executor: gcr.io/kaniko-project/executor:latest

# TODO: https://github.com/snok/container-retention-policy
# TODO: Push a build image before the final image
# TODO: Run basic tests with build image
# TODO: Push final image only if tests pass https://redhat-cop.github.io/ci/publishing-images.html
