on:
  push:
    branches:
      - main
jobs:
  flutter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Get latest Flutter tag
        id: query
        uses: actions/github-script@v6
        with:
          script: |
            const query = `query GetLatestTags {
              repository(owner: "flutter", name: "flutter") {
                tags: refs(
                  refPrefix: "refs/tags/"
                  first: 10
                  orderBy: { field: TAG_COMMIT_DATE, direction: DESC }
                ) {
                  edges {
                    node {
                      version: name
                      target {
                        oid
                      }
                    }
                  }
                }
              }
            }`;

            const rawResult = await github.graphql(query)
            const regex = /^(\d+\.)+\d+(?!-)$/g
            const tags = rawResult.repository.tags.edges
            const latestTag = tags.find((tag) => tag.node.version.match(regex))

            const fs = require('fs');
            const data = fs.readFileSync('version.json', 'utf8');
            const json = JSON.parse(data);

            const result = {
              ...json,
              flutter: {
                version: latestTag.node.version,
                commit: latestTag.node.target.oid
              }
            }

            return result
      
      - name: Write latest Flutter tag to file
        run: |
          echo '${{ steps.query.outputs.result }}' 
          echo '${{ steps.query.outputs.result }}' > flutter_version.json

# TODO: https://github.com/flutter-actions/setup-flutter

