on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  flutter:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update latest Flutter version
        uses: actions/github-script@v6
        with:
          script: |
              const script = require('./script/updateFlutterVersion.js')
              await script({github, core, fetch})
      
      - name: Update latest Fastlane version
        uses: actions/github-script@v6
        with:
          script: |
              const script = require('./script/updateFastlaneVersion.js')
              await script({core, fetch})

      - name: Setup Flutter
        uses: flutter-actions/setup-flutter@v2
        with:
          cache: true
          channel: ${{ env.FLUTTER_CHANNEL }}
          version: ${{ env.FLUTTER_VERSION }}

      # TODO: Create test app in specific folder with step id, to allow parallel execution
      - name: Create test application
        run: |
          flutter create test_app

      # TODO: Cache gradle https://github.com/gradle/gradle-build-action
      - name: Update default Android platform versions in Flutter
        working-directory: test_app/android
        run: |
          cat ../../script/updateAndroidVersions.gradle >> app/build.gradle
          ./gradlew --warning-mode all updateAndroidVersions

      - name: Clean test application
        run: |
          rm -rf test_app

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          cache: 'npm'
          cache-dependency-path: docs/src/package-lock.json

      - name: Update documentation
        working-directory: docs/src
        run: |
          npm ci --prefer-offline
          npm run build

      - name: Create pull request if there are changes
        uses: peter-evans/create-pull-request@v5
